version: '3'

services:
  charehjo:
    build: .
    command: gunicorn charehjo.wsgi:application --bind=0.0.0.0:8000 --log-level=debug
    volumes:
      - .:/my_app_dir
    ports:
      - "8003:8000"
