# Generated by Django 4.2.3 on 2023-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='education',
            field=models.CharField(blank=True, choices=[('کمتر از کارشناسی', 'کمتر از کارشناسی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری'), ('دیگر', 'دیگر')], default='A4', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('کمتر از یک سال', 'کمتر از یک سال'), ('بین یک تا سه سال', 'بین یک تا سه سال'), ('بین سه تا پنج سال', 'بین سه تا پنج سال'), ('بیشتر از پنج سال', 'بیشتر از پنج سال')], default='A4', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.CharField(blank=True, choices=[('علاقه مند یا دانشجو', 'علاقه مند یا دانشجو'), ('دستیار مدیر محصول', 'دستیار مدیر محصول'), ('مدیر محصول', 'مدیر محصول'), ('مدیر محصول ارشد', 'مدیر محصول ارشد')], default='A4', max_length=100, null=True),
        ),
    ]
