# Generated by Django 4.2.3 on 2023-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_myuser_education_myuser_experience_myuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='free',
            field=models.BooleanField(default=False, verbose_name='پلن رایگان'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='moghadamati',
            field=models.BooleanField(default=False, verbose_name='پلن مقدماتی'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pro',
            field=models.BooleanField(default=False, verbose_name='پلن پیشرفته'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='takmili',
            field=models.BooleanField(default=False, verbose_name='پلن تکمیلی'),
        ),
    ]
